AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Max: 30
